# -*- coding: utf-8 -*-
"""script_LorenzoDallaCostaCervelin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhyUbp5OYVfjk3Tee9yEnDhrYeSSPN-G

# 1. Importação dos dados e bibliotecas

Para o devido funcionamento do código abaixo, certifique-se de fazer o upload da base de dados sob o nome `Base Varejo.csv` no sistema de arquivos do Google Colab.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Base Varejo.csv', sep=';')

# Preview dos dados carregados

df.info()
df.head()

"""# 2. Limpeza dos dados

Pelo output do `.info()`, percebemos a existência de categorias vazias, bem como colunas com tipos de dados inadequados. Segue-se a deleção das categorias e o tratamrnto de dados irregulares. A versão limpa do dataset é então exportada como um arquivo `df_limpo.csv`.
"""

# Cria cópia do dataframe para limpeza
df_limpo = df.copy()

# Checa valores nulos por coluna
for col in df_limpo.columns:
    print("Na coluna "+col+" existem "+str(df_limpo[col].isnull().sum())+" valores nulos")

# Checa se existem valores duplicados
temDuplicados = df_limpo.duplicated().any()
if temDuplicados:
    print("Existem "+str(df_limpo.duplicated().sum())+" valores duplicados.")
else:
    print("Não existem valores duplicados.")

# Deleta colunas vazias e valores duplicados
df_limpo = df_limpo.dropna(how='all', axis='columns')
if temDuplicados:
  df_limpo.drop_duplicates(inplace=True)

# Deleta itens sem identificação de ID de compra ou de cliente
df_limpo.dropna(subset=['CO_ID', 'CL_ID'], how='any')

# Preenche categorias de produto nulas com a string "Sem Categoria"
temCatVazia = df_limpo['PR_CAT'].isna().any()
if temCatVazia:
    df_limpo['PR_CAT'] = df['PR_CAT'].fillna("Sem Categoria")
    print("Categorias vazias encontradas.")
else: print("Não existem categorias vazias.")

# Corrige o tipo de dado das colunas
df_limpo['DATA'] = pd.to_datetime(df_limpo['DATA'], format='%d/%m/%Y')
df_limpo = df_limpo.astype({"CL_GENERO": "string", "CL_SEG": "string", "PR_CAT": "string", "PR_NOME": "string"})

df_limpo.to_csv('df_limpo.csv')
df_limpo.info()

"""# 3. Exploração dos dados
Uma vez tratados os dados, segue-se para a realização das tarefas de exploração descritiva.

##### 3.1 Estatísticas da coluna `CL_FHL`
"""

print(f"Estatística descritiva - número de filhos por cliente")
print(f"Média: {df_limpo['CL_FHL'].mean()}")
print(f"Mediana: {df_limpo['CL_FHL'].median()}")
print(f"Desvio Padrão: {df_limpo['CL_FHL'].std()}")
print(f"Moda: {df_limpo['CL_FHL'].mode().tolist()}")
print(f"Máximo: {df_limpo['CL_FHL'].max()}")
print(f"Mínimo: {df_limpo['CL_FHL'].min()}")
print(f"Contagem: {df_limpo['CL_FHL'].count()}")

"""##### 3.2 Tamanho médio da cesta de compras por número de filhos"""

# Agrupar por compra e número de filhos para calcular o volume de compras (número de produtos) por compra
tamanhoCesta_por_compra = df_limpo.groupby(['CO_ID', 'CL_FHL']).size().reset_index(name='num_produtos')

# Agrupar pelo número de filhos e calcular a média de produtos por compra para cada grupo de filhos
cestaPorFilho = tamanhoCesta_por_compra.groupby('CL_FHL')['num_produtos'].mean()

print("Número médio de produtos por compra, por número de filhos:")
display(media_produtos_por_filho)

"""##### 3.3 Volume mensal de vendas"""

# Extrair o mês da data
df_limpo['MES'] = df_limpo['DATA'].dt.month

# Calcular o volume de vendas (número de itens) por mês
volumeMensal = df_limpo['MES'].value_counts().sort_index()

# Criar o histograma (gráfico de barras é mais adequado para meses)
plt.figure(figsize=(12, 6))
sns.barplot(x=volumeMensal.index, y=volumeMensal.values)
plt.title('Volume de Vendas por Mês do Ano')
plt.xlabel('Mês do Ano')
plt.ylabel('Volume de Vendas (Número de Itens)')
plt.xticks(ticks=range(0, 12), labels=['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'])
plt.show()

print("Volume de vendas por mês:")
display(volumeMensal)

"""# 4. Conclusões

Pela exploração dos dados acima, os seguintes insights foram obtidos:
1. A grande maioria dos clientes não possui filhos.
2. O número de filhos por cliente não interfere no tamanho médio das compras
3. O mês com pior performance de vendas da série histórica, visto de maneira agregada, é novembro.
"""